// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiPageWebApp.Models;

namespace MultiPageWebApp.Migrations
{
    [DbContext(typeof(ContactsContext))]
    [Migration("20210208195513_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("MultiPageWebApp.Models.Contacts", b =>
                {
                    b.Property<int>("ContactsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ContactsId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactsId = 1,
                            Address = "1122 Over Here Dr",
                            Name = "Hayley",
                            Note = "Wifey",
                            Number = "515-555-1234"
                        },
                        new
                        {
                            ContactsId = 2,
                            Address = "123 Over There Ct",
                            Name = "Griff",
                            Note = "Son",
                            Number = "515-555-4321"
                        },
                        new
                        {
                            ContactsId = 3,
                            Address = "987 Where St",
                            Name = "Beck",
                            Note = "Son",
                            Number = "515-555-1324"
                        },
                        new
                        {
                            ContactsId = 4,
                            Address = "7890 Doghouse Ln",
                            Name = "Wally",
                            Note = "Woof",
                            Number = "515-555-9876"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
